[package]
name = "paraos_libkernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paraos_libwasm = { path = "../libwasm" }
spin = "0.9.2"
x86 = "0.45.0"